run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - unused
    - gofmt

issues:
  exclude-rules:
    # Exclude 'unused' errors in the plugins directory, as these are expected for now.
    - path: plugins/
      linters:
        - unused
